email validation on sign-in and register
boolean-uk/team-dev-client-ex-2410-team1 pull request #17
Opened 2024-10-28 10:33 UTC by DagAndreas

2024-10-28 10:36 UTC, JosteinRuen reviewed
Looks good!

2024-10-28 10:37 UTC, JosteinRuen submitted a review, later dismissed
Amazing work

2024-10-28 10:38 UTC, johnfa1508 submitted a review, later dismissed
Looks good Dag

2024-10-28 12:07 UTC, johnfa1508 submitted a review, later dismissed
Looks good Dag

2024-10-28 12:07 UTC, JosteinRuen approved these changes
Great work

2024-10-28 12:30 UTC, dogezen requested changes
1) please move the validation logic into separate helper functions so that they can be reused
2) make sure the user sees some text telling them the email is invalid / the password is invalid, otherwise they don't know why the form is disabled
3) remove console.logs once the code is working

2024-10-28 12:30 UTC, dogezen commented on src/pages/login/index.js
> +  const isValidPassword = () => {
this function is repeated twice, once in login and once in registration. Please move it into an utils.js file and call it something like:

```js
validatePassword(password) { // name is indicative, you can choose a different name
....
}
```

The function should return true/false.

2024-10-28 12:30 UTC, dogezen commented on src/pages/login/index.js
> +  const isValidEmail = () => {
see comment for password, please move the validation logic in a utils / helper function so that it can be reused

2024-10-28 12:30 UTC, dogezen commented on src/pages/login/index.js
> +    console.log(
remove console log once code is working

2024-10-28 12:30 UTC, dogezen commented on src/pages/register/index.js
> +    console.log('Email Valid: ', validRegex.test(formData.email), '. Email: ', formData.email);
remove console log

2024-10-28 12:30 UTC, dogezen commented on src/pages/register/index.js
> +    console.log(
remove console log

2024-10-28 12:30 UTC, dogezen commented on src/pages/register/index.js
> +    isValidEmail(formData.email);
isValidEmail returns a value, but you're not using that value...

2024-10-28 12:30 UTC, dogezen commented on src/pages/register/index.js
> +    isValidPassword(formData.password);
isValidPassword returns a value but you're not using it

2024-10-28 12:30 UTC, dogezen commented on src/pages/login/index.js
>          </div>
you should also add a red label / text around the form field, or the entire form explaining to the user that the email is not valid or the form is not valid

2024-10-29 08:30 UTC, DennisOsmani commented
DennisOsmani/Uthmel-#14-login/register_Inputvalidation

2024-10-29 08:33 UTC, johnfa1508 approved these changes
Looks very good Melvin and Dennis

2024-10-29 08:34 UTC, JosteinRuen approved these changes
Good job fixing the requested changes

2024-10-29 08:46 UTC, allendewilzin commented
👍🏻

2024-10-29 08:46 UTC, allendewilzin approved these changes
Well done on changes

2024-10-29 08:46 UTC, allendewilzin commented
Just mark each issue raised as Resolved.

2024-10-29 08:50 UTC, merged

2024-10-29 09:04 UTC, JosteinRuen reviewed
Great job adding error messages for usability 👍