31 - Julia and Melvin - cohort page   student view
boolean-uk/team-dev-client-ex-2410-team1 pull request #35
Opened 2024-10-31 14:45 UTC by uthmel

2024-10-31 14:48 UTC, JosteinRuen submitted a review, later dismissed
Amazing work, great functionality. We will look at the styling later 👍

2024-10-31 14:49 UTC, johnfa1508 approved these changes, later dismissed
This is amazing!

2024-10-31 14:56 UTC, dogezen requested changes, later dismissed
1) please update the API call - see feedback
2) ideally, please update getting the logged in user id from auth context and not by parsing token
3) create an issue in backlog to refactor this component so that it can be reused to see any cohort page by cohort id -> this can be ignored for tomorrow, and would be an issue to work on next week, for example, or early tomorrow morning if you wish
4) rename the file to MyCohort.jsx -> although I think the name would be better as `CohortPage`

2024-10-31 14:56 UTC, dogezen commented on src/service/apiClient.js
> +export { login, getPosts, register, createProfile, get };
don't expose `get` -> create instead a getUsers function instead in `apiClient.js` and export that function.

2024-10-31 14:56 UTC, dogezen commented on src/pages/cohort/myCohort.js
> +    const loggedInId = jwtDecode(token).userId;
loggedinuser can be obtained from auth context, no need to decode the token

2024-11-01 09:21 UTC, allendewilzin approved these changes, later dismissed

2024-11-01 09:22 UTC, allendewilzin commented
Ensure you have your branch updated with main.

2024-11-01 09:39 UTC, allendewilzin approved these changes

2024-11-01 09:42 UTC, johnfa1508 approved these changes

2024-11-01 09:43 UTC, merged